//
//  AnyPropertyPublisher.swift
//  Relay
//
//  Created by Kamil Strzelecki on 17/01/2025.
//  Copyright © 2025 Kamil Strzelecki. All rights reserved.
//

import Combine

/// An object that exposes `Combine` publishers for  ``willChange`` and ``didChange`` events.
///
/// Subclasses of this class are generated by the ``Publishable()`` macro, and provide publishers
/// for all mutable or computed instance properties of the type the macro is applied to.
///
open class AnyPropertyPublisher<Object: AnyObject> {

    private let _willChange = PassthroughSubject<Object, Never>()
    private let _didChange = PassthroughSubject<Object, Never>()

    /// Emits the `Object` **before** any of its stored properties are assigned a new value.
    ///
    public var willChange: AnyPublisher<Object, Never> {
        _willChange.eraseToAnyPublisher()
    }

    /// Emits the `Object` **after** any of its stored properties are assigned a new value.
    ///
    public var didChange: AnyPublisher<Object, Never> {
        _didChange.eraseToAnyPublisher()
    }

    private var pendingModifications = 0
    private unowned let object: Object

    @_documentation(visibility: private)
    public init(object: Object) {
        self.object = object
    }

    deinit {
        _willChange.send(completion: .finished)
        _didChange.send(completion: .finished)
    }
}

// swiftlint:disable identifier_name

extension AnyPropertyPublisher {

    public func _beginModifications() {
        pendingModifications += 1
        if pendingModifications == 1 {
            _willChange.send(object)
        }
    }

    public func _endModifications() {
        if pendingModifications == 1 {
            _didChange.send(object)
        }
        pendingModifications -= 1
    }
}

extension AnyPropertyPublisher {

    public func _storedPropertyPublisher<T>(
        _ subject: PassthroughSubject<T, Never>,
        for keyPath: KeyPath<Object, T>
    ) -> AnyPublisher<T, Never> {
        subject
            .prepend(object[keyPath: keyPath])
            .eraseToAnyPublisher()
    }
}

extension AnyPropertyPublisher {

    public func _computedPropertyPublisher<T>(
        for keyPath: KeyPath<Object, T>
    ) -> AnyPublisher<T, Never> {
        _didChange
            .prepend(object)
            .map { $0[keyPath: keyPath] }
            .eraseToAnyPublisher()
    }

    public func _computedPropertyPublisher<T: Equatable>(
        for keyPath: KeyPath<Object, T>
    ) -> AnyPublisher<T, Never> {
        _didChange
            .prepend(object)
            .map { $0[keyPath: keyPath] }
            .removeDuplicates()
            .eraseToAnyPublisher()
    }

    public func _computedPropertyPublisher<T: AnyObject>(
        for keyPath: KeyPath<Object, T>
    ) -> AnyPublisher<T, Never> {
        _didChange
            .prepend(object)
            .map { $0[keyPath: keyPath] }
            .removeDuplicates { $0 === $1 }
            .eraseToAnyPublisher()
    }

    public func _computedPropertyPublisher<T: AnyObject & Equatable>(
        for keyPath: KeyPath<Object, T>
    ) -> AnyPublisher<T, Never> {
        _didChange
            .prepend(object)
            .map { $0[keyPath: keyPath] }
            .removeDuplicates()
            .eraseToAnyPublisher()
    }
}

// swiftlint:enable identifier_name
