//
//  AnyPropertyPublisher.swift
//  Relay
//
//  Created by Kamil Strzelecki on 17/01/2025.
//  Copyright © 2025 Kamil Strzelecki. All rights reserved.
//

import Combine

/// An object that exposes `Combine` publishers for  ``willChange`` and ``didChange`` events.
///
/// Subclasses of this class are generated by the ``Publishable()`` macro, and provide publishers
/// for all mutable or computed instance properties of the type the macro is applied to.
///
open class AnyPropertyPublisher {

    private final let _willChange = PassthroughSubject<Void, Never>()
    private final let _didChange = PassthroughSubject<Void, Never>()

    /// Emits the `Object` **before** any of its stored properties are assigned a new value.
    ///
    public final var willChange: some Publisher<Void, Never> {
        _willChange
    }

    /// Emits the `Object` **after** any of its stored properties are assigned a new value.
    ///
    public final var didChange: some Publisher<Void, Never> {
        _didChange
    }

    private final var pendingModifications = 0

    @_documentation(visibility: private)
    public init(object _: AnyObject) {}

    deinit {
        _willChange.send(completion: .finished)
        _didChange.send(completion: .finished)
    }
}

// swiftlint:disable identifier_name

extension AnyPropertyPublisher {

    public final func _beginModifications() {
        pendingModifications += 1
        if pendingModifications == 1 {
            _willChange.send(())
        }
    }

    public final func _endModifications() {
        if pendingModifications == 1 {
            _didChange.send(())
        }
        pendingModifications -= 1
    }
}

extension AnyPropertyPublisher {

    public final func _storedPropertyPublisher<Object, T>(
        _ subject: PassthroughSubject<T, Never>,
        for keyPath: KeyPath<Object, T>,
        object: Object
    ) -> some Publisher<T, Never>
    where Object: AnyObject {
        subject.prepend(object[keyPath: keyPath])
    }
}

extension AnyPropertyPublisher {

    public final func _computedPropertyPublisher<Object, T>(
        for keyPath: KeyPath<Object, T>,
        object: Object
    ) -> some Publisher<T, Never>
    where Object: AnyObject {
        _didChange
            .prepend(())
            .map { [unowned object] in
                object[keyPath: keyPath]
            }
    }

    public final func _computedPropertyPublisher<Object, T>(
        for keyPath: KeyPath<Object, T>,
        object: Object
    ) -> some Publisher<T, Never>
    where Object: AnyObject, T: Equatable {
        _didChange
            .prepend(())
            .map { [unowned object] in
                object[keyPath: keyPath]
            }
            .removeDuplicates()
    }

    public final func _computedPropertyPublisher<Object, T>(
        for keyPath: KeyPath<Object, T>,
        object: Object
    ) -> some Publisher<T, Never>
    where Object: AnyObject, T: AnyObject {
        _didChange
            .prepend(())
            .map { [unowned object] in
                object[keyPath: keyPath]
            }
            .removeDuplicates { lhs, rhs in
                lhs === rhs
            }
    }

    public final func _computedPropertyPublisher<Object, T>(
        for keyPath: KeyPath<Object, T>,
        object: Object
    ) -> some Publisher<T, Never>
    where Object: AnyObject, T: AnyObject & Equatable {
        _didChange
            .prepend(())
            .map { [unowned object] in
                object[keyPath: keyPath]
            }
            .removeDuplicates()
    }
}

// swiftlint:enable identifier_name
