//
//  PublishableProtocol.swift
//  Relay
//
//  Created by Kamil Strzelecki on 23/11/2025.
//  Copyright © 2025 Kamil Strzelecki. All rights reserved.
//

import Observation

/// A type that can be observed using both the `Observation` and `Combine` frameworks.
///
/// You don't need to declare conformance to this protocol yourself.
/// It is generated automatically when you apply the ``Publishable()`` macro to your type.
///
public protocol Publishable: AnyObject, Observable {

    /// A subclass of ``AnyPropertyPublisher`` generated by the ``Publishable()`` macro,
    /// containing publishers for all mutable or computed instance properties of the type.
    ///
    associatedtype PropertyPublisher: AnyPropertyPublisher

    /// An instance that exposes `Combine` publishers for all mutable or computed instance properties of the type.
    ///
    /// - Important: Don't store this instance in an external property. Accessing it after the original object has been deallocated
    /// may result in a crash. Always access it directly through the object that exposes it.
    ///
    var publisher: PropertyPublisher { get }
}
